# =========================
# SERVER
# =========================
server.port=8080

# URL del sistema (ajustada al mismo puerto)
app.system.url=http://localhost:8080/login


# =========================
# DATASOURCE (SQL SERVER)
# =========================
spring.datasource.url=jdbc:sqlserver://54.39.102.101:1433;databaseName=vacaciones_dev;encrypt=false;trustServerCertificate=true
spring.datasource.username=UserPrueba
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# (Opcional: Hibernate ya detecta el dialecto solo)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


# =========================
# THYMELEAF
# =========================
spring.thymeleaf.cache=false


# =========================
# MAIL (BREVO)
# =========================
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=desarrollo.movil@inssoftmx.com
spring.mail.password=6wVcjd7W0kFyEHhp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Debug opcional
# spring.mail.properties.mail.debug=true


# =========================
# ENCODING
# =========================
spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


# =========================
# LOGGING
# =========================
logging.level.root=INFO
logging.level.com.mx.vacaciones=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger - %msg%n

logging.file.name=C:\\logs\\vacaciones.log


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB